### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by DamonHD** [MSDarshan91/AES_GCM#1]
Hi,

What is the licence for this code, please?

Rgds

Damon

**Comment by DamonHD** [comment]
And FWIW, I'd prefer a BSD/MIT/Apache flavour of licence if at all possible...  B^>

Rgds

Damon

**Comment by MSDarshan91** [comment]
I would say MIT license.

**Comment by DamonHD** [comment]
Cool: can you set one up at top level please, for the world to see?  I think it may be a single button for you to press on your project front page.

My slight preference is Apache 2.0, since that's what we use in OpenTRV, and I can bore you with why if you wish!

(Without the licence visible it's effectively not open source at all...)

Rgds

Damon

**Comment by MSDarshan91** [comment]
I would like to know the difference between the 3 licenses.

**Comment by DamonHD** [comment]
This is _the_ place to understand the different OS licences:

http://opensource.org/

I think that it is fair to describe Apache as the most modern of the widely-used and well-understood permissive (eg business-friendly) licences, and has some provisions to make things such as patent trolling difficult, which is why I like it.

Rgds

Damon

**Comment by DamonHD** [comment]
That looks good!  Hope it means that more people can make use of your implementation!
